name: nlp-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nltk
  - pip
  - pip:
    - django
    - djangorestframework
    - django-cors-headers
    - django-tailwind
    - PySide6
    - PySide6_Addons
    - PySide6_Essentials
    - tqdm

