name: nlp-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nltk
  - psycopg2
  - postgresql
  - pip
  - pip:
    - django
    - djangorestframework
    - django-cors-headers
    - django-tailwind
    - python-decouple
    - joblib
    - gunicorn
