name: nlp-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - click=8.1.7
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.2
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mysql=5.7.24
  - ncurses=6.4
  - nltk=3.8.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.14
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.0
  - ply=3.11
  - psycopg2=2.9.9
  - pybind11-abi=5
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - qt-main=5.15.2
  - readline=8.2
  - regex=2023.10.3
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.66.4
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asgiref==3.8.1
      - django==5.0.7
      - django-cors-headers==4.4.0
      - django-tailwind==3.8.0
      - djangorestframework==3.15.2
      - python-decouple==3.8
      - sqlparse==0.5.1